language: android

android:
  components:
   - tools
   - platform-tools
   - build-tools-26.0.2
   - android-19

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
 # Install NDK + openconnect build deps
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential autoconf automake libtool groff expect ant
 - FORCE_PKG=android_ndk ./misc/fetch.sh android-ndk-r16b-linux-x86_64.zip bcdea4f5353773b2ffa85b5a9a2ae35544ce88ec5b507301d8cf6a76b765d901
 - sudo mkdir -p /opt/android-sdk-linux_x86
 - sudo unzip -d /opt/android-sdk-linux_x86 -q android-ndk-r16b-linux-x86_64.zip

script:
 - make -C external
 - ./gradlew assembleDebug

after_success:
 - mkdir -p artifacts/ics-openconnect/{arm,arm64,x86,x86_64}
 - ln -s artifacts/ics-openconnect out
 - cp app/build/outputs/apk/debug/app-debug.apk out/OpenConnect-debug.apk
 - cp app/libs/* out/
 - cp app/src/main/jniLibs/armeabi/* out/arm/
 - cp app/src/main/jniLibs/arm64-v8a/* out/arm64/
 - cp app/src/main/jniLibs/x86/* out/x86/
 - cp app/src/main/jniLibs/x86_64/* out/x86_64/
 # skip directories (will return an error code)
 - cp external/arm/* out/arm/ || true
 - cp external/arm64/* out/arm64/ || true
 - cp external/x86/* out/x86/ || true
 - cp external/x86_64/* out/x86_64/ || true
 - cp external/arm/openconnect/android/arm-linux-androideabi/out/sbin/openconnect out/arm/
 - cp external/arm64/openconnect/android/aarch64-linux-android/out/sbin/openconnect out/arm64/
 - cp external/x86/openconnect/android/i686-linux-android/out/sbin/openconnect out/x86/
 - cp external/x86_64/openconnect/android/x86_64-linux-android/out/sbin/openconnect out/x86_64/

deploy:
  provider: gcs
  access_key_id: GOOGCQGVURTSQZ7ZO637
  secret_access_key:
    secure: Hy80IYriHUvwUii4OULL3/RoDs6QXLhKkffIj3cK7oAfZ4M6Lqu60/Xm411T/fLIlgChSuJwWn2o2o7G3rtW7bxSictz1HoC+jrcUM6EB6h78LJUxnUcBwSxqIGmkGM3EguxhBPOlDxcYiAMavUG1s+O0X8T/JIvgPh0CmvfDag=
  bucket: cernekee-travis
  local-dir: artifacts
  skip_cleanup: true
  acl: public-read
  on:
    repo: cernekee/ics-openconnect
    all_branches: true
