slanguage: java
jdk: oraclejdk7

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  # Install base Android SDK
    - sudo apt-get update -qq
    - sudo apt-get install -qq libstdc++6:i386 lib32z1 build-essential autoconf automake libtool groff expect
    - export COMPONENTS=build-tools-19.1.0,android-19,sysimg-19,extra-android-support
    - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/master/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
    - source ~/.android-sdk-installer/env
    - curl -L http://dl.google.com/android/ndk/android-ndk-r9d-linux-x86_64.tar.bz2 > ndk.tar.bz2
    - sudo tar -C /opt -jxf ndk.tar.bz2
    - android update project -p . -s

script:
    - rm -rf libs/*.jar libs/armeabi assets/raw/armeabi
    - make -C external NDK=/opt/android-ndk-r9d ARCH_LIST=arm
    - ant debug
